---
name: "YAML: Syntax checks"

"on":
  workflow_call:

jobs:
  yaml:
    name: "YAML"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
      - id: yamllint
        name: "Yamllint: Check yaml files"
        run: |
          yamllint -c .yamllint.yaml ./
