---
name: "Terraform: Code checks"

"on":
  workflow_call:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
      - id: tf_version
        name: "Terraform: Get version"
        run: |
          TF_VERSION=$(cat .terraform-version 2>/dev/null || echo latest)
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_OUTPUT
      - id: tf_setup
        name: "Terraform: Setup"
        uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800  # v3.1.0
        with:
          terraform_version: ${{steps.tf_version.outputs.TF_VERSION}}
      - id: tf_fmt
        name: "Terraform: Check formatting"
        run: terraform fmt -check -diff -recursive ./
      - id: tf_init
        name: "Terraform: Prepare working directory"
        run: terraform init
      - id: tf_validate
        name: "Terraform: Check configuration is valid"
        run: terraform validate
  tfdocs:
    name: "Documentation"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
      - id: tfdocs
        name: "Terraform-Docs: Check Documentation"
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6  # v1.1.0
        with:
          fail-on-diff: true
  tflint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
      - id: tflint_cache
        name: "TFLint: Update cache"
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - id: tflint_setup
        name: "TFLint: Setup"
        uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987  # v4.0.0
      - id: tflint_init
        name: "TFLint: Install plugins"
        run: tflint --init
      - id: tflint_inspect
        name: "TFLint: Inspect code"
        run: tflint -f compact --module
