---
name: "YAML: Syntax checks"

"on":
  workflow_call:

jobs:
  yaml:
    name: "YAML"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - id: yamllint
        name: "Yamllint: Check yaml files"
        run: |
          yamllint -c .yamllint.yaml ./
