---
name: "Python: Syntax checks"

"on":
  workflow_call:

jobs:
  shell:
    name: "Python application"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - id: black
        name: "Black: check python formatting"
        uses: rickstaa/action-black@d86849e16a3c498947d70be55198feb86d5d4f53  # v1.3.3
