---
name: "YAML: Syntax checks"

"on":
  workflow_call:

jobs:
  yaml:
    name: "YAML"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - id: yamllint
        name: "Yamllint: Check yaml files"
        run: |
          yamllint -c .yamllint.yaml ./
