---
name: "Terraform: Apply Changes"

"on":
  workflow_call:
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - id: tf_version
        name: "Terraform: Get version"
        run: |
          TF_VERSION=$(cat .terraform-version 2>/dev/null || echo latest)
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_OUTPUT
      - id: tf_setup
        name: "Terraform: Setup"
        uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800  # v3.1.0
        with:
          terraform_version: ${{steps.tf_version.outputs.TF_VERSION}}
      - id: tf_init
        name: "Terraform: Prepare working directory"
        run: terraform init
      - id: tf_apply
        name: "Terraform: Apply terraform plan"
        run: terraform apply -auto-approve -input=false -no-color
