---
name: "Python: Syntax checks"

"on":
  workflow_call:

jobs:
  shell:
    name: "Python application"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
      - id: black
        name: "Black: check python formatting"
        uses: rickstaa/action-black@d86849e16a3c498947d70be55198feb86d5d4f53  # v1.3.3
