---
name: "Shell: Syntax checks"

"on":
  workflow_call:

jobs:
  shell:
    name: "Shell scripts"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
      - id: shhellcheck
        name: "Shellcheck: check scripts"
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38  # v2.0.0
