---
name: "Shell: Syntax checks"

"on":
  workflow_call:

jobs:
  shell:
    name: "Shell scripts"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - id: shhellcheck
        name: "Shellcheck: check scripts"
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38  # v2.0.0
