---
name: "Terraform Module: Code checks"

"on":
  workflow_call:
jobs:
  terraform:
    name: "Terraform Module"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - id: tf_version
        name: "Terraform: Get version"
        run: |
          TF_VERSION=$(cat .terraform-version 2>/dev/null || echo latest)
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_OUTPUT
      - id: tf_setup
        name: "Terraform: Setup"
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
          terraform_version: ${{steps.tf_version.outputs.TF_VERSION}}
      - id: tf_fmt
        name: "Terraform: Check formatting"
        run: terraform fmt -check -diff -recursive ./
      - name: "Terraform: Cache providers directory"
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
        with:
          path: ./.terraform/providers
          key: tf-${{ steps.tf_version.outputs.TF_VERSION }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.terraform.lock.hcl') }}
      - id: tf_init
        name: "Terraform: Prepare working directory"
        run: terraform init -backend=false
      - id: tf_validate
        name: "Terraform: Check configuration is valid"
        run: terraform validate
  tfdocs:
    name: "Module documentation"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - id: tfdocs
        name: "Terraform-Docs: Check Documentation"
        uses: terraform-docs/gh-actions@cca78c27ac9e2b6545debf2ecae9df930fd3461c  # v1.2.2
        with:
          fail-on-diff: true
  tflint:
    name: "Module linting"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - id: tflint_cache
        name: "TFLint: Update cache"
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - id: tflint_setup
        name: "TFLint: Setup"
        uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987  # v4.0.0
      - id: tflint_init
        name: "TFLint: Install plugins"
        run: tflint --init
      - id: tflint_inspect
        name: "TFLint: Inspect code"
        run: tflint -f compact --call-module-type=local
