---
name: "YAML: Syntax checks"

"on":
  workflow_call:

jobs:
  yaml:
    name: "YAML"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - id: yamllint
        name: "Yamllint: Check yaml files"
        run: |
          yamllint -c .yamllint.yaml ./
