---
name: "YAML: Syntax checks"

"on":
  workflow_call:

jobs:
  yaml:
    name: "YAML"
    runs-on: ubuntu-latest
    steps:
      - id: repo_checkout
        name: "Repository: Checkout"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
      - id: yamllint
        name: "Yamllint: Check yaml files"
        run: |
          yamllint -c .yamllint.yaml ./
